name = "x"
type = "javascript"
workers_dev = true
compatibility_date = "2021-11-18"

[site]
bucket = "dist/client"
entry-point = "."

[build]
command = ""
watch_dir = "dist/worker"

[build.upload]
format = "service-worker"
