name: Build

on:
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run build
        env:
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ZD1LFTxtIhuKo9ShGvlojYHFAhEw-Whpj2l8ymip
        env:
          CF_ACCOUNT_ID: d1574ff4d207bc23602cc79fc78b7b2a
